name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-deb-rpm:
    name: Create DEB and RPM Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install RPM Build Dependencies (on Ubuntu host)
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential

      - name: Calculate Variables
        id: vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          else
            VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "DEB_ARCHITECTURE=${ARCHITECTURE:-all}" >> $GITHUB_ENV
          echo "RPM_ARCHITECTURE=${ARCHITECTURE:-noarch}" >> $GITHUB_ENV

      - name: Build and Package DEB (inside Debian Docker container)
        uses: addnab/docker-run-action@v3
        with:
          image: debian:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir
          shell: bash
          run: |
            set -e
            set -u
            set -o pipefail

            apt-get update
            apt-get install -y dpkg-dev build-essential lintian pkg-config libgtk-3-dev
            make
            mkdir -p build/deb/usr/bin
            cp life-switch build/deb/usr/bin/
            strip build/deb/usr/bin/life-switch
            mkdir -p build/deb/DEBIAN
            mkdir -p build/deb/usr/lib/systemd/system
            cp life-switch.service build/deb/usr/lib/systemd/system/
            mkdir -p build/deb/usr/share/doc/life-switch

            # Use echo and pipe to cat, then redirect
            echo -e "life-switch (${{ env.VERSION }}) unstable; urgency=medium\n\n  * Initial release.\n\n -- ${{ env.MAINTAINER_NAME }} <${{ env.GITHUB_EMAIL }}>  $(date -R)" | cat > build/deb/usr/share/doc/life-switch/changelog.Debian.gz
            gzip -9 build/deb/usr/share/doc/life-switch/changelog.Debian

            # Use echo and pipe to cat, then redirect
            echo -e "Copyright (C) $(date +%Y) ${{ env.MAINTAINER_NAME }}\n\nThis program is free software; you can redistribute it and/or modify\nit under the terms of the MIT License. See the LICENSE file\nfor details." | cat > build/deb/usr/share/doc/life-switch/copyright

            # Use echo and pipe to cat, then redirect
            echo -e "Package: life-switch\nVersion: ${{ env.VERSION }}\nArchitecture: amd64\nMaintainer: ${{ env.MAINTAINER_NAME }} <${{ env.GITHUB_EMAIL }}>\nDepends: libgtk-3-0, \${shlibs:Depends}\nPriority: optional\nSection: utils\nDescription: Simple GTK application.\n This application serves as a basic GTK example." | cat > build/deb/DEBIAN/control

            # Use echo and pipe to cat, then redirect
            echo -e "#!/bin/sh\nset -e\nif ! id -u life_switch >/dev/null 2>&1; then\n  useradd -r -s /usr/sbin/nologin -M life_switch\nfi\nsystemctl daemon-reload\nsystemctl enable life-switch.service\nsystemctl start life-switch.service" | cat > build/deb/DEBIAN/postinst

            # Use echo and pipe to cat, then redirect
             echo -e "#!/bin/sh\nset -e\nsystemctl stop life-switch.service\nsystemctl disable life-switch.service" | cat > build/deb/DEBIAN/prerm
            chmod +x build/deb/DEBIAN/postinst
            chmod +x build/deb/DEBIAN/prerm
            dpkg-deb --build build/deb life-switch_${{ env.VERSION }}_amd64.deb
            lintian --pedantic --info --show-overrides life-switch_${{ env.VERSION }}_amd64.deb

      - name: Build RPM package
        run: |
          set -e
          set -u
          mkdir -p SOURCES SPECS RPMS
          cp life-switch SOURCES/
          strip SOURCES/life-switch
          cp life-switch.service SOURCES/

          #Use echo with -e
          echo -e "Name:           ${{ env.PACKAGE_NAME }}\nVersion:        ${{ env.VERSION }}\nRelease:        1%{?dist}\nSummary:        ${{ env.APP_DESCRIPTION }}\nLicense:        MIT\nBuildArch:      ${{ env.RPM_ARCHITECTURE }}\nBuildRequires:  gtk3-devel\nRequires:       gtk3\n\n%description\n${{ env.APP_DESCRIPTION }}\n\n%prep\n%build\nmake\n\n%install\nmkdir -p %{buildroot}/usr/bin\ninstall -m 755 life-switch %{buildroot}/usr/bin/\nmkdir -p %{buildroot}/usr/lib/systemd/system\ninstall -m 644 %{_sourcedir}/life-switch.service %{buildroot}/usr/lib/systemd/system/\n\n%files\n/usr/bin/life-switch\n/usr/lib/systemd/system/life-switch.service\n\n%pre\ngetent passwd life_switch >/dev/null || useradd -r -s /usr/sbin/nologin -M life_switch\n\n%post\nsystemctl daemon-reload\nsystemctl enable ${{ env.PACKAGE_NAME }}.service\nsystemctl start ${{ env.PACKAGE_NAME }}.service || :\n\n%preun\nsystemctl stop ${{ env.PACKAGE_NAME }}.service || :\n\n%postun\nsystemctl disable ${{ env.PACKAGE_NAME }}.service\nif [ \$1 -eq 0 ]; then\n    true\nfi\n\n%changelog\n* $(date -R) ${{ env.MAINTAINER_NAME }} <${{ env.GITHUB_EMAIL }}> - ${{ env.VERSION }}-1\n- Initial release." > SPECS/${{ env.PACKAGE_NAME }}.spec

          rpmbuild -bb SPECS/${{ env.PACKAGE_NAME }}.spec

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            RPMS/**/*.rpm
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        if: github.ref_type == 'tag'
