name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-deb-rpm:
    name: Create DEB and RPM Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install RPM Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm rpm-build build-essential

      - name: Calculate Variables
        id: vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          else
            VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "GITHUB_EMAIL=${GITHUB_ACTOR}@users.noreply.github.com" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "DEB_ARCHITECTURE=amd64" >> $GITHUB_ENV
          echo "RPM_ARCHITECTURE=x86_64" >> $GITHUB_ENV
          echo "APP_DESCRIPTION=Simple GTK application." >> $GITHUB_ENV
          echo "MAINTAINER_NAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Build and Package DEB
        uses: addnab/docker-run-action@v3
        with:
          image: debian:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir
          shell: bash
          run: |
            set -euxo pipefail
            apt-get update
            apt-get install -y dpkg-dev build-essential lintian pkg-config libgtk-3-dev
            make
            mkdir -p build/deb/usr/bin
            cp life-switch build/deb/usr/bin/
            strip build/deb/usr/bin/life-switch
            mkdir -p build/deb/DEBIAN
            mkdir -p build/deb/usr/lib/systemd/system
            cp life-switch.service build/deb/usr/lib/systemd/system/
            mkdir -p build/deb/usr/share/doc/life-switch

            # Changelog
            printf "life-switch (%s) unstable; urgency=medium\n\n  * Initial release.\n\n -- %s <%s>  %s\n" \
              "${{ env.VERSION }}" "${{ env.MAINTAINER_NAME }}" "${{ env.GITHUB_EMAIL }}" "$(date -R)" \
              > build/deb/usr/share/doc/life-switch/changelog.Debian
            gzip -9 build/deb/usr/share/doc/life-switch/changelog.Debian

            # Copyright
            echo "Copyright (C) $(date +%Y) ${{ env.MAINTAINER_NAME }}
              This program is free software; you can redistribute it and/or modify
              it under the terms of the MIT License.  See the LICENSE file
              for details." > build/deb/usr/share/doc/life-switch/copyright

            # Control file
            printf "Package: life-switch\n" > build/deb/DEBIAN/control
            printf "Version: %s\n" "${{ env.VERSION }}" >> build/deb/DEBIAN/control
            printf "Architecture: %s\n" "${{ env.DEB_ARCHITECTURE }}" >> build/deb/DEBIAN/control
            printf "Maintainer: %s <%s>\n" "${{ env.MAINTAINER_NAME }}" "${{ env.GITHUB_EMAIL }}" >> build/deb/DEBIAN/control
            printf "Depends: libgtk-3-0, ${shlibs:Depends}\n" >> build/deb/DEBIAN/control
            printf "Priority: optional\n" >> build/deb/DEBIAN/control
            printf "Section: utils\n" >> build/deb/DEBIAN/control
            printf "Description: Simple GTK application.\n This application serves as a basic GTK example.\n" >> build/deb/DEBIAN/control

            # postinst
            printf '#!/bin/sh\nset -e\nif ! id -u life_switch >/dev/null 2>&1; then\n  useradd -r -s /usr/sbin/nologin -M life_switch || :\nfi\nsystemctl daemon-reload\nsystemctl enable life-switch.service\nsystemctl start life-switch.service || :\n' > build/deb/DEBIAN/postinst

            # prerm
            printf '#!/bin/sh\nset -e\nsystemctl stop life-switch.service || :\nsystemctl disable life-switch.service || :\n' > build/deb/DEBIAN/prerm

            chmod +x build/deb/DEBIAN/postinst build/deb/DEBIAN/prerm
            dpkg-deb --build build/deb life-switch_"${{ env.VERSION }}"_"${{ env.DEB_ARCHITECTURE }}".deb
            lintian --pedantic --info --show-overrides life-switch_"${{ env.VERSION }}"_"${{ env.DEB_ARCHITECTURE }}".deb

      - name: Build RPM package
        run: |
          set -euxo pipefail
          mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS}
          cp life-switch rpmbuild/SOURCES/
          strip rpmbuild/SOURCES/life-switch
          cp life-switch.service rpmbuild/SOURCES/

          printf "Name: %s\nVersion: %s\nRelease: 1%%{?dist}\nSummary: %s\nLicense: MIT\nBuildArch: %s\nBuildRequires: gtk3-devel\nRequires: gtk3\n\n%%description\n%s\n\n%%prep\n\n%%build\nmake\n\n%%install\nmkdir -p %%{buildroot}/usr/bin\ninstall -m 755 life-switch %%{buildroot}/usr/bin/\nmkdir -p %%{buildroot}/usr/lib/systemd/system\ninstall -m 644 %%{_sourcedir}/life-switch.service %%{buildroot}/usr/lib/systemd/system/\n\n%%files\n/usr/bin/life-switch\n/usr/lib/systemd/system/life-switch.service\n\n%%pre\ngetent passwd life_switch >/dev/null || useradd -r -s /usr/sbin/nologin -M life_switch || :\n\n%%post\nsystemctl daemon-reload\nsystemctl enable %s.service\nsystemctl start %s.service || :\n\n%%preun\nsystemctl stop %s.service || :\n\n%%postun\nsystemctl disable %s.service || :\n\n%%changelog\n* %s %s <%s> - %s-1\n- Initial release.\n" \
            "${{ env.PACKAGE_NAME }}" "${{ env.VERSION }}" "${{ env.APP_DESCRIPTION }}" "${{ env.RPM_ARCHITECTURE }}" "${{ env.APP_DESCRIPTION }}" \
            "${{ env.PACKAGE_NAME }}" "${{ env.PACKAGE_NAME }}" "${{ env.PACKAGE_NAME }}" "${{ env.PACKAGE_NAME }}" \
            "$(date -R)" "${{ env.MAINTAINER_NAME }}" "${{ env.GITHUB_EMAIL }}" "${{ env.VERSION }}" \
            > rpmbuild/SPECS/"${{ env.PACKAGE_NAME }}".spec

          rpmbuild -bb --define "_topdir $(pwd)/rpmbuild" rpmbuild/SPECS/"${{ env.PACKAGE_NAME }}".spec
          mv rpmbuild/RPMS/${{ env.RPM_ARCHITECTURE }}/*.rpm .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        if: github.ref_type == 'tag'
