name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build-deb-rpm:
    name: Create DEB and RPM Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install RPM Build Dependencies (on Ubuntu host)
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential

      - name: Calculate Variables
        id: vars
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          else:
            VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          echo "DEB_ARCHITECTURE=${ARCHITECTURE:-all}" >> $GITHUB_ENV
          echo "RPM_ARCHITECTURE=${ARCHITECTURE:-noarch}" >> $GITHUB_ENV

      - name: Build and Package DEB (inside Debian Docker container)
        uses: addnab/docker-run-action@v3
        with:
          image: debian:latest
          options: -v ${{ github.workspace }}:/workdir -w /workdir
          shell: bash
          run: |
            set -e
            set -u
            set -o pipefail

            apt-get update
            apt-get install -y dpkg-dev build-essential lintian pkg-config libgtk-3-dev
            make
            mkdir -p build/deb/usr/bin
            cp life-switch build/deb/usr/bin/
            strip build/deb/usr/bin/life-switch
            mkdir -p build/deb/DEBIAN
            mkdir -p build/deb/usr/lib/systemd/system
            cp life-switch.service build/deb/usr/lib/systemd/system/
            mkdir -p build/deb/usr/share/doc/life-switch

            # Corrected escaping using printf
            printf "life-switch (%s) unstable; urgency=medium\n\n  * Initial release.\n\n -- %s <%s>  %s\n" "${{ env.VERSION }}" "${{ env.MAINTAINER_NAME }}" "${{ env.GITHUB_EMAIL }}" "$(date -R)" > build/deb/usr/share/doc/life-switch/changelog.Debian

            # THEN compress it
            gzip -9 build/deb/usr/share/doc/life-switch/changelog.Debian

            # Use > (folded style) and explicit newlines (CORRECTED)
            echo "Copyright (C) $(date +%Y) ${{ env.MAINTAINER_NAME }}
              This program is free software; you can redistribute it and/or modify
              it under the terms of the MIT License.  See the LICENSE file
              for details." > build/deb/usr/share/doc/life-switch/copyright

            # Use > (folded style) and explicit newlines (CORRECTED)
            echo "Package: life-switch
              Version: ${{ env.VERSION }}
              Architecture: amd64
              Maintainer: ${{ env.MAINTAINER_NAME }} <${{ env.GITHUB_EMAIL }}>
              Depends: libgtk-3-0, \${shlibs:Depends}
              Priority: optional
              Section: utils
              Description: Simple GTK application.
               This application serves as a basic GTK example." > build/deb/DEBIAN/control

            # Use > (folded style) and explicit newlines (CORRECTED)
            echo "#!/bin/sh
              set -e
              if ! id -u life_switch >/dev/null 2>&1; then
                useradd -r -s /usr/sbin/nologin -M life_switch
              fi
              systemctl daemon-reload
              systemctl enable life-switch.service
              systemctl start life-switch.service" > build/deb/DEBIAN/postinst

            # Use > (folded style) and explicit newlines (CORRECTED)
            echo "#!/bin/sh
              set -e
              systemctl stop life-switch.service
              systemctl disable life-switch.service" > build/deb/DEBIAN/prerm

            chmod +x build/deb/DEBIAN/postinst
            chmod +x build/deb/DEBIAN/prerm
            dpkg-deb --build build/deb life-switch_${{ env.VERSION }}_amd64.deb
            lintian --pedantic --info --show-overrides life-switch_${{ env.VERSION }}_amd64.deb

      - name: Build RPM package
        run: |
          set -e
          set -u
          mkdir -p SOURCES SPECS RPMS
          cp life-switch SOURCES/
          strip SOURCES/life-switch
          cp life-switch.service SOURCES/
          # correct rpm spec file
          echo "
Name:           ${{ env.PACKAGE_NAME }}
Version:        ${{ env.VERSION }}
Release:        1%{?dist}
Summary:        ${{ env.APP_DESCRIPTION }}
License:        MIT
BuildArch:      ${{ env.RPM_ARCHITECTURE }}
BuildRequires:  gtk3-devel
Requires:       gtk3

%description
${{ env.APP_DESCRIPTION }}

%prep
%build
make

%install
mkdir -p %{buildroot}/usr/bin
install -m 755 life-switch %{buildroot}/usr/bin/
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 644 %{_sourcedir}/life-switch.service %{buildroot}/usr/lib/systemd/system/

%files
/usr/bin/life-switch
/usr/lib/systemd/system/life-switch.service

%pre
getent passwd life_switch >/dev/null || useradd -r -s /usr/sbin/nologin -M life_switch

%post
systemctl daemon-reload
systemctl enable ${{ env.PACKAGE_NAME }}.service
systemctl start ${{ env.PACKAGE_NAME }}.service || :

%preun
systemctl stop ${{ env.PACKAGE_NAME }}.service || :

%postun
systemctl disable ${{ env.PACKAGE_NAME }}.service
if [ \$1 -eq 0 ]; then
    true
fi

%changelog
* $(date -R) ${{ env.MAINTAINER_NAME }} <${{ env.GITHUB_EMAIL }}> - ${{ env.VERSION }}-1
- Initial release.
" > SPECS/${{ env.PACKAGE_NAME }}.spec
          rpmbuild -bb SPECS/${{ env.PACKAGE_NAME }}.spec

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            RPMS/**/*.rpm
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        if: github.ref_type == 'tag'
